baseURL = "https://haflidif.github.io/devcontainer-template"
languageCode = "en-us"
title = "DevContainer Template for Infrastructure as Code"

# Build configuration to handle deprecation warnings
logLevel = "warn"
buildFuture = true
buildExpired = true
ignoreErrors = ["error-missing-instagram-accesstoken"]

# Required for Geekdoc theme
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true
defaultContentLanguage = "en"

# Hugo module configuration for Geekdoc theme
[module]
  [[module.imports]]
    path = "github.com/thegeeklab/hugo-geekdoc"

# Site description and metadata
[params]
  version = "v2.0"
  description = "A comprehensive DevContainer template for Terraform and Bicep development with modern testing, automation, and documentation."
  github_repo = "https://github.com/haflidif/devcontainer-template"
  github_branch = "main"
  
  # Edit page settings
  geekdocEditPage = true
  geekdocRepo = "https://github.com/haflidif/devcontainer-template"
  geekdocBranch = "main"
  
  # Search settings
  geekdocSearch = true
  
  # Footer settings
  geekdocLegalNotice = ""
  geekdocPrivacyPolicy = ""
  
  # Theme settings
  geekdocMenuBundle = false
  geekdocNextPrev = true
  geekdocBackToTop = true
  
  # Social media settings (replaces deprecated .Site.Social)
  social = []

# Menu configuration
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/haflidif/devcontainer-template"
  weight = 50

# Markup configuration for code highlighting
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    hl_inline = false
    lineAnchors = ""
    tabWidth = 4

# Language settings
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "DevContainer Template Documentation"
