# Pre-commit configuration for Infrastructure as Code projects
# Supports both Terraform and Bicep
# Copy this to your project root as .pre-commit-config.yaml
# Run: pre-commit install

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - --args=--only=terraform_deprecated_interpolation
          - --args=--only=terraform_deprecated_index
          - --args=--only=terraform_unused_declarations
          - --args=--only=terraform_comment_syntax
          - --args=--only=terraform_documented_outputs
          - --args=--only=terraform_documented_variables
          - --args=--only=terraform_typed_variables
          - --args=--only=terraform_module_pinned_source
          - --args=--only=terraform_naming_convention
          - --args=--only=terraform_required_version
          - --args=--only=terraform_required_providers
          - --args=--only=terraform_standard_module_structure
      - id: terraform_tfsec
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact

  # Azure Bicep hooks
  - repo: local
    hooks:
      - id: bicep-build
        name: Bicep Build
        entry: bicep build
        language: system
        files: '\.bicep$'
        pass_filenames: true

      - id: bicep-lint
        name: Bicep Lint
        entry: bicep lint
        language: system
        files: '\.bicep$'
        pass_filenames: true

      - id: bicep-format
        name: Bicep Format
        entry: bicep format
        language: system
        files: '\.bicep$'
        pass_filenames: true

  # PSRule for Azure (if PowerShell is available)
  - repo: local
    hooks:
      - id: psrule-azure
        name: PSRule Azure Analysis
        entry: pwsh
        language: system
        args:
          [
            "-c",
            "Invoke-PSRule -Format File -InputPath . -Module PSRule.Rules.Azure",
          ]
        files: '\.(bicep|json)$'
        pass_filenames: false
